version: '3'
services:
  httpd:
    environment:
      - HOST_URL=http://webapp:8000
      # - XDEBUG_MODE=debug
      # - XDEBUG_MODE=off
      # - XDEBUG_CONFIG=
      # - XDEBUG_SESSION=
    extra_hosts:
      - "webapp:127.0.0.1"
    healthcheck:
      test: curl http://localhost:8000/sei || exit 1
      interval: 1ms
      timeout: 1m
      retries: 300

  php-test:
    image: processoeletronico/vagrant_super4_httpd:${ENVIRONMENT_VERSION}
    working_dir: /project
    command: "true"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/project
    environment:
      - LANG=pt_BR.ISO-8859-1
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 start_with_request=0
      - XDEBUG_SESSION=default
      - XDEBUG_MODE=debug

  php-test-func:
    extends:
      file: docker-compose.test.yml
      service: php-test
    environment:
      - LANG=pt_BR.ISO-8859-1
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 start_with_request=0
      - XDEBUG_SESSION=default
      - XDEBUG_MODE=debug
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - SEI_CHAVE_ACESSO=${SEI_CHAVE_ACESSO}
      - SEI_DATABASE_NAME=${SEI_DATABASE_NAME}
      - SEI_DATABASE_USER=${SEI_DATABASE_USER}
      - SEI_DATABASE_PASSWORD=${SEI_DATABASE_PASSWORD}
      - SIP_CHAVE_ACESSO=${SIP_CHAVE_ACESSO}
      - SIP_DATABASE_NAME=${SIP_DATABASE_NAME}
      - SIP_DATABASE_USER=${SIP_DATABASE_USER}
      - SIP_DATABASE_PASSWORD=${SIP_DATABASE_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/project
    depends_on:
      selenium:
        condition: "service_healthy"
      httpd:
        condition: service_healthy
    links:
      - database:${DATABASE_HOST}
      - selenium:selenium

  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    healthcheck:
      test: curl http://localhost:4444/wd/hub/status || exit 1
      interval: 3s
      timeout: 10s
      retries: 5
    links:
      - httpd:webapp
