version: '2'
services:
  jod:
    image: processoeletronico/vagrant_super4_jod:${ENVIRONMENT_VERSION}

  smtp:
    image: processoeletronico/vagrant_super4_mailcatcher:${ENVIRONMENT_VERSION}
    container_name: smtp
    ports:
      - "1080:1080"

  memcached:
    image: processoeletronico/vagrant_super4_memcached:${ENVIRONMENT_VERSION}
    container_name: memcached
    ports:
      - "11211:11211"

  database:
    image: ${DATABASE_IMAGE}:${ENVIRONMENT_VERSION}
    container_name: ${DATABASE_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword
    volumes:
      - ${DATABASE_HOST}:${DATABASE_DATA_DIR}
      - /var/sei/backup/${DATABASE_HOST}:/backup
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

  solr:
    image: processoeletronico/vagrant_super4_solr:${ENVIRONMENT_VERSION}
    container_name: solr
    ports:
      - "8983:8983"

  httpd:
    image: processoeletronico/vagrant_super4_httpd:${ENVIRONMENT_VERSION}
    container_name: httpd
    restart: always
    env_file:
      - .modulo.env
    ports:
      - "80:8000"
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ${SEI_PATH}/sei:/opt/sei
      - ${SEI_PATH}/sip:/opt/sip
      - ${SEI_PATH}/infra:/opt/infra
      - ./envs/config/ConfiguracaoSEI.php:/opt/sei/config/ConfiguracaoSEI.php:ro
      - ./envs/config/ConfiguracaoSip.php:/opt/sip/config/ConfiguracaoSip.php:ro
      - ./src:/opt/sei/web/modulos/resposta
      - ./src/scripts:/opt/sei/scripts/mod-resposta
      - ./src/scripts:/opt/sip/scripts/mod-resposta
      - .:/project
    environment:
      - LANG=pt_BR.ISO-8859-1
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 start_with_request=0
      - XDEBUG_SESSION=default
      - XDEBUG_MODE=debug
      - HOST_URL=${SEI_HOST}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}

      - SEI_CHAVE_ACESSO=${SEI_CHAVE_ACESSO}
      - SEI_DATABASE_NAME=${SEI_DATABASE_NAME}
      - SEI_DATABASE_USER=${SEI_DATABASE_USER}
      - SEI_DATABASE_PASSWORD=${SEI_DATABASE_PASSWORD}

      - SIP_CHAVE_ACESSO=${SIP_CHAVE_ACESSO}
      - SIP_DATABASE_NAME=${SIP_DATABASE_NAME}
      - SIP_DATABASE_USER=${SIP_DATABASE_USER}
      - SIP_DATABASE_PASSWORD=${SIP_DATABASE_PASSWORD}
    links:
      - database:${DATABASE_HOST}
      - memcached:memcached
      - solr:solr
      - smtp:smtp
      - jod:jod

volumes:
  mysql:
  oracle:
  sqlserver:
